name: build and test feature branch
on:
  push:
    branches:
      - 'feature/*'
jobs:
  build-feature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        run: |
          echo "Pulling and checking out the code from the repository..."

      - name: Set up Node.js 22
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Install npm packages
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli@latest
         
      - name: Build Angular app
        run: ng build --prod